// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/landing-page/CommandCenter.tsx": () => import("../components/mockups/landing-page/CommandCenter.tsx"),
  "./components/mockups/landing-page/HumanFocus.tsx": () => import("../components/mockups/landing-page/HumanFocus.tsx"),
  "./components/mockups/landing-page/KineticGrid.tsx": () => import("../components/mockups/landing-page/KineticGrid.tsx")
};
